
### Get all books
GET http://localhost:4004/odata/v4/Catalog/Books HTTP/1.1

#### Create a new book
POST http://localhost:4004/odata/v4/Catalog/Books
Content-Type: application/json

{
  "title": "New Book Title",
  "stock": 15
}

